### ISSUE TITLE
[BUG]무기 정보창 이슈

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#106]
**이슈 요약**
[무기 관련] 
무기 UI의 위치가 변경됨

**이슈 내용**
버그 내용 상세하게 작성
무기 UI의 위치가 좌측 화면가에서 무기 옆으로 변경되었습니다.
**재현 스텝**
: 스텝별로 상세하게 작성
1. 
2. 
3. 
4. 

**일자**
날짜 작성

**Comment by Z1758** [comment]
![수정3](https://github.com/user-attachments/assets/c44c6b7f-b85a-4565-a677-472d427a278d)
ui를 좀 더 좌측으로 이동 시켰습니다

**Comment by jgb0222** [comment]
혹시 각도도 무기 교체 UI와 같은 각도로 가능한가요?

**Comment by Z1758** [comment]
![제목 없음](https://github.com/user-attachments/assets/77fe0c4b-a5dc-4c66-9d23-2079d0a28c99)
수정했습니다

**Comment by jgb0222** [comment]
감사합니다
