### ISSUE TITLE
[BUG]2스테이지 성 진입 멀미

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#109]
**이슈 요약**
[맵 관련] 버그 요약 한줄로 작성
멀미가 너무 심함

**이슈 내용**
결사를 내려갈 때 기울어져 있어서 멀미가 심하게 나는 것 같은데 자이로 스코프 처럼 경사로에서도 평지와 똑같은 각도로 보이게 하면 멀미가 덜 할 것 같습니다.
**재현 스텝**
: 스텝별로 상세하게 작성
1. 성 진입
2. 
3. 
4. 

**일자**
날짜 작성

**Comment by Z1758** [comment]
![수정2](https://github.com/user-attachments/assets/63b7d5ac-6c48-4824-8064-41952802e243)

성 진입시 이동속도를 낮추고 각도를 올려다보게 변경했습니다

**Comment by jgb0222** [comment]
감사합니다
