### ISSUE TITLE
[BUG][무기 관련] 총 먹통

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#167]
**이슈 요약**
[무기 관련/장전/방어 관련/승패/적/캐릭터/맵/기능] 버그 요약 한줄로 작성
쉴드 올리고 쉴드 깨진 후에 장전과 발사가 안됨

**이슈 내용**
버그 내용 상세하게 작성
좌측 트리거로 쉴드를 올리고 이후 쉴드가 깨진 후에 장전을 비롯한 다른 행동이 안됨(쉴드 깨질때 다른 기능 막는 것 끄기)

**재현 스텝**
: 스텝별로 상세하게 작성
1.좌측 트리거로 쉴드 생성 
2. 이후 깨질 때까지 기다림
3. 깨진후 좌측 그립버튼 , 우측 트리거 버튼, 우측 그립 버튼 작동 안됨 
4. 

**일자**
날짜 작성

**Comment by Z1758** [comment]
![수정](https://github.com/user-attachments/assets/bf3a0e97-5609-4c16-a5fa-a498ad3f8261)

수정했습니다

**Comment by jgb0222** [comment]
감사합니다
