### ISSUE TITLE
[BUG][장전 관련] 발사 중 장전 가능

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#177]
**이슈 요약**
[장전] 버그 요약 한줄로 작성
무기 발사 시 첫발을 발사한 후 그 즉시 장전을 진행하게 되면 장전 쿨타임을 기다리지 않아도 되는 기능
**이슈 내용**
버그 내용 상세하게 작성
첫발을 발사 후 그 즉시 장전을 진행하게 되면 탄창에 표시되는 총알수와 다르게 모든 총알이 장전이 되어 장전 쿨타임을 기다리지 않아도 되는 문제가 있는데 이거를 고치게 되면 난이도적으로 많이 올라가서 잡기술로 생각하는게 좋을지 의견 부탁 드립니다.

**재현 스텝**
: 스텝별로 상세하게 작성
1. 우측 트리거를 눌러 총알 1발 발사
2. 이후 좌측 그립버튼 누름
3. 총알을 전부 소모할때까지 발사 진행 
4. 장전

**일자**
날짜 작성

**Comment by Z1758** [comment]
장전 중에 발사하면 장전이 취소되게 할까요?

**Comment by jgb0222** [comment]
냅두는 것도 좋을 것 같아서요

**Comment by Z1758** [comment]
![수정](https://github.com/user-attachments/assets/45359da5-0ad5-48a6-89a6-21cf92c91f7e)

표기를 실시간 적용 시켰습니다

**Comment by jgb0222** [comment]
감사합니다
