### ISSUE TITLE
[BUG]특수 무기 총알 없애기

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#182]
**이슈 요약**
[무기 관련/장전/방어 관련/승패/적/캐릭터/맵/기능] 버그 요약 한줄로 작성
특수 무기의 총알이 시작시 없어야 한다.

**이슈 내용**
버그 내용 상세하게 작성
시작 시 무기 교체창을 열었을 때 특수 무기에 총알이 남아 있다.

**재현 스텝**
: 스텝별로 상세하게 작성
1. 게임 시작 후 우측 그립 버튼 누름
2. 
3. 
4. 

**일자**
2024.11.04

**Comment by Z1758** [comment]
시연용으로 남겼습니다 최종 빌드때 빼겠습니다

**Comment by jgb0222** [comment]
감사합니다
