### ISSUE TITLE
[BUG][적 관련]거미 공격 이슈

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#183]
**이슈 요약**
[적] 버그 요약 한줄로 작성
거미의 공격이 안보인다.
**이슈 내용**
버그 내용 상세하게 작성
거미의 공격의 투사체를 설정해놨는데 이 투사체가 안보인다. 
**재현 스텝**
: 스텝별로 상세하게 작성
1. 3웨이브에서 거미 출현 시
2. 
3. 
4. 

**일자**
날짜 작성

**Comment by leesiyeon99** [comment]
거미 투사체 보이도록 수정했습니다

**Comment by jgb0222** [comment]
감사합니다
