### ISSUE TITLE
[BUG]무기 교체 UI 이미지

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#185]
**이슈 요약**
[장전] 버그 요약 한줄로 작성
무기 교체시 선택되는 무기를 표시하는 UI의 가운데 부분을 전달 드리는 이미지로 변경해 주세요

**이슈 내용**
무기 교체시 선택되는 무기를 표시하는 가운데에 있는 UI의 이미지를 전달 드리는 이미지로 변경해 주세요
(제거)
**재현 스텝**
: 스텝별로 상세하게 작성
1. 우측 그립버튼을 눌렀을 때
2. 
3. 
4. 

**일자**
날짜 작성

**Comment by Z1758** [comment]
![제목 없음](https://github.com/user-attachments/assets/8b084ffc-3195-42a0-8d48-542210f43123)
수정했습니다

**Comment by jgb0222** [comment]
감사합니다
