### ISSUE TITLE
[BUG][적 관련] 거미 투사체

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#193]
**이슈 요약**
[적] 버그 요약 한줄로 작성
조준점이 투사체에 생성됨

**이슈 내용**
3웨이브에서 거미줄을 조준했을 때 거미줄에 조준점이 생성됨
**재현 스텝**
: 스텝별로 상세하게 작성
1. 3웨이브 진입
2. 조준점을 거미줄에 가져다 댐
3. 
4. 

**일자**
2024.11.04

**Comment by leesiyeon99** [comment]
수정했습니다.

**Comment by jgb0222** [comment]
감사합니다

**Comment by LeeJaeHo-96** [comment]
개발 일정 종료되어 Won`t Fix로 처리하겠습니다.
