### ISSUE TITLE
[BUG][적 관련] 거미 투사체 안사라짐

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#194]
**이슈 요약**
[적] 버그 요약 한줄로 작성
거미 투사체가 맞고 나서도 사라지지 않음
**이슈 내용**
버그 내용 상세하게 작성
거미줄을 맞았을 때 거미줄이 유저 캐릭터에 맞고도 사라지지 않는다.

**재현 스텝**
: 스텝별로 상세하게 작성
1. 3웨이브 진입 후 거미줄 맞음
2. 
3. 
4. 

**일자**
날짜 작성

**Comment by leesiyeon99** [comment]
거미줄 발사하고 5초 뒤에 삭제되도록 해놓았습니다.

**Comment by jgb0222** [comment]
감사합니다
