### ISSUE TITLE
[BUG][적 관련] 거미줄 장전속도 체크

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#195]
**이슈 요약**
[적] 버그 요약 한줄로 작성
거미줄을 맞았을 때 장전 속도가 느려지는 것이 체감이 안됨

**이슈 내용**
버그 내용 상세하게 작성
거미줄을 맞았을 때 달라지는 수치를 확인해 주세요

**재현 스텝**
: 스텝별로 상세하게 작성
1. 3웨이브 진입 후 거미줄 맞기
2. 
3. 
4. 

**일자**
2024.11.04

**Comment by leesiyeon99** [comment]
수정했습니다 거미줄에 맞으면 장전속도 0.5-> 0.7로 변경됩니다.

**Comment by jgb0222** [comment]
감사합니다
