### ISSUE TITLE
[BUG][무기 관련] 2스테이지 폭팔 무기

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#197]
**이슈 요약**
[무기 관련] 
2스테이지 폭팔 무기의 장전 양이 정해진 갯수가 아니다

**이슈 내용**
2스테이지에서 폭발 무기의 장전 탄약량이 6이어야 하는데 50발이 장전됨

**재현 스텝**
: 스텝별로 상세하게 작성
1. 2스테이지 진입
2. 
3. 
4. 

**일자**
2024.11.04

**Comment by Z1758** [comment]
2스테이지 4번 무기만 시연용 치트무기로 만들었습니다

**Comment by jgb0222** [comment]
확인되었습니다
