### ISSUE TITLE
[BUG][캐릭터 관련]피격시 효과음 재생 안됨

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#199]
**이슈 요약**
[캐릭터] 버그 요약 한줄로 작성
적에게 피격시 표과음의 재생이 안된다.

**이슈 내용**
버그 내용 상세하게 작성
에셋 리스트 스테이지 1의 아랫 부분에 적혀있는 대로 피격시 소리가 나야 하는데 나오지 않음

**재현 스텝**
: 스텝별로 상세하게 작성
1. 적에게 피격 시
2. 
3. 
4. 

**일자**
2024.11.04

**Comment by LeeJaeHo-96** [comment]
수정되었습니다. 다음 빌드에서 확인 부탁드립니다.

**Comment by jgb0222** [comment]
감사합니다
