### ISSUE TITLE
[BUG] 교수님이 작성한 것과 양식이 달라요

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#30]
**이슈 요약**
[무기 관련/장전/방어 관련/승패/적/캐릭터/맵/기능] 버그 요약 한줄로 작성
양식이 다른데 혹시 괜찮나요?
라벨 한글로 바꿔주세요

**이슈 내용**
버그 내용 상세하게 작성
![bandicam 2024-10-29 18-06-58-927](https://github.com/user-attachments/assets/6aca1cf0-5c8a-4928-8310-605b97149e12)
**재현 스텝**
: 스텝별로 상세하게 작성
1. 
2. 
3. 
4. 

**일자**
날짜 작성

**Comment by LeeJaeHo-96** [comment]
버그 리포트의 경우 현재 양식으로 진행하는 것으로 합의되었습니다.
감사합니다.
