### ISSUE TITLE
[BUG][무기 관련] 컨트롤러에 생성되는 총의 각도 이슈

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#31]
**이슈 요약**
무기 위치 이슈

**이슈 내용**
시스템 기획서 내의 내용으로 총 위치 수정
![bandicam 2024-10-30 11-36-41-845](https://github.com/user-attachments/assets/5db1f23c-e975-4ecd-9728-16aa8508c6cc)

**재현 스텝**
접속 시

**일자**
2024.10.30

**Comment by Z1758** [comment]
![제목 없음](https://github.com/user-attachments/assets/e7cd1a4a-7482-443c-9809-d0abdc79eeec)
수정했습니다
