### ISSUE TITLE
[BUG][무기 관련] 무기의 단발 발사 미구현

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#32]
**이슈 요약**
[무기 관련/장전/방어 관련/승패/적/캐릭터/맵/기능] 버그 요약 한줄로 작성
무기 단발 발사 기능이 안됨

**이슈 내용**
기본 무기가 연발로 발사됨 

**재현 스텝**
: 스텝별로 상세하게 작성
우측 트리거를 누를 때
발사가 연속적으로 진행됨

**일자**
2024.10.30

**Comment by Z1758** [comment]
단발 기능은 구현 되어 있습니다

연사 가속 기능 테스트 용으로 

기본무기에 연사 특성과 티어3을 적용 했습니다
