### ISSUE TITLE
[BUG][무기 관련] 무기 정보 UI 위치 이슈

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#33]
**이슈 요약**
위치가 잘못됨

**이슈 내용**
해당 UI의 위치는 총을 따라가는 것이 아니라 유저 화면 좌측 중앙 부근에 고정되어 있다.

**재현 스텝**
: 스텝별로 상세하게 작성
좌측 그립 버튼을 눌렀을 때

**일자**
날짜 작성

**Comment by Z1758** [comment]
![제목 없음](https://github.com/user-attachments/assets/eb19c7d9-ac57-4b3b-a771-22eeb9a5bfce)

UI 분리하고 페이드 아웃 적용 시켰습니다

**Comment by jgb0222** [comment]
확인 되었습니다
