### ISSUE TITLE
[BUG] 깃허브 버그 리포트 작성 중 라벨을 찾기가 힘들다

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#34]
**이슈 요약**
리포트 작성 중 라벨을 찾기 불편합니다.
**이슈 내용**
리포트 작성 중 라벨을 찾기 불편합니다.
혹시 시간 남으시면 위급 순서대로 정렬 가능한가요?

**재현 스텝**
없음

**일자**
날짜 작성

**Comment by LeeJaeHo-96** [comment]
라벨 정렬은 시스템상 불가합니다.
감사합니다.

**Comment by jgb0222** [comment]
확인했습니다
