### ISSUE TITLE
[BUG][무기 관련] 조준점 위치 문제

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#35]
**이슈 요약**
[무기 관련]
조준점이 적이나 물체 표면에 안나타난다.

**이슈 내용**
조준점이 적 표면에 생성되지 않고 일정한 위치에 고정되어 있다

**재현 스텝**
: 스텝별로 상세하게 작성
1.  적 혹은 물체 조준시 

**일자**
2024.10.30

**Comment by Z1758** [comment]
조준점의 레이어 마스크와 

생성 되지 않는 물체의 레이어가 맞지 않아 발생하는 문제 같습니다

레이어 마스크를 모든 레이어로 변경 하겠습니다

**Comment by Z1758** [comment]
![1](https://github.com/user-attachments/assets/932cb349-1f7c-4f74-978d-3febd226a575)
![2](https://github.com/user-attachments/assets/767a9086-a266-451f-9344-9cd05e9c6719)
![3](https://github.com/user-attachments/assets/c5526aa4-6ada-4083-9b95-d694f5a205d3)

**Comment by jgb0222** [comment]
확인 되었습니다
