### ISSUE TITLE
[BUG][캐릭터] 무기 교체 UI 선택 표시 부분

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#45]
**이슈 요약**
[캐릭터]
무기 교체 UI 에서 가운데 선택된 무기를 표시하는 부분(이미지에서 R)의 위치가 의도와 다르다.

**이슈 내용**
무기 교체 UI 에서 가운데 선택된 무기를 표시하는 부분(이미지에서 R)이 위를 각 무기의 중앙인 45도 135도 225도 315도에만 위치해야 한다.
선택 무기 표시 부분은 아래 이미지 4 상태만 존재한다.
![image](https://github.com/user-attachments/assets/bd375ae4-3d05-4030-a397-a7086341270f)

**재현 스텝**
: 스텝별로 상세하게 작성
1. 아무 버튼도 누르지 않은 상태에서 우측 그립 버튼 누름
2. 우측 엄지 버튼을 움직인다.
3. 
4. 

**일자**
2024.10.30

**Comment by Z1758** [comment]
![gif](https://github.com/user-attachments/assets/75bda7ed-a476-45c3-90a7-7f0cc9391cdc)
수정했습니다

**Comment by jgb0222** [comment]
감사합니다
