### ISSUE TITLE
[BUG]장전중 무기 변경 가능

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#87]
**이슈 요약**
[무기][장전]
장전 중에 무기 변경이 가능함

**이슈 내용**
장전 중에는 무기의 변경이 진행되면 안되는데 장전 중에 무기 변경이 가능해서 장전 쿨타임을 무기하는게 가능해졌다.

**재현 스텝**
: 스텝별로 상세하게 작성
1. 좌측 그립 버튼 클릭
2. 우측 그립 버튼 틀릭
3. 장전 완료 전에 무기 변경
4. 변경된 무기에 장전 진행

**일자**
2024.11.02

**Comment by Z1758** [comment]
장전 중에 교체 창이 뜨지 않도록 수정했습니다

**Comment by jgb0222** [comment]
감사합니다
