### ISSUE TITLE
[BUG][무기]{장전} 장전 이슈

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#91]
**이슈 요약**
[무기 관련/장전/방어 관련/승패/적/캐릭터/맵/기능] 버그 요약 한줄로 작성
일부 위치에서 장전 진행이 안됨
**이슈 내용**
우측 컨트롤러와 좌측 컨트롤러를 가까이 하고 장전을 진행할 경우 탄창이 생성되더라도 장전이 안됨

**재현 스텝**
: 스텝별로 상세하게 작성
1. 우측 컨트롤러와 좌측 컨트롤러를 가까이 붙인다
2. 좌측 컨트롤러의 그립 버튼을 누르고 기다린다.
3. 
4. 

**일자**
날짜 작성

**Comment by Z1758** [comment]
![수정](https://github.com/user-attachments/assets/c7524a70-1fa2-4ac2-ac95-387e84218b21)
수정했습니다

**Comment by jgb0222** [comment]
감사합니다
