### ISSUE TITLE
[BUG]요정이 안보여요

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#93]
**이슈 요약**
[기능] 버그 요약 한줄로 작성
맵 내에 요정이 안보임

**이슈 내용**
초반에 가까워질 때 너무 가까워져서 텍스트 전체를 눈으로 파악하기 힘들고 이후 위치가 눈에 잘 들어오지 않게 된다.

**재현 스텝**
: 스텝별로 상세하게 작성
1. 게임 시작후 컷씬
2. 
3. 
4. 

**일자**
날짜 작성

**Comment by Z1758** [comment]
![수정](https://github.com/user-attachments/assets/446e75a3-e26c-4d79-a55c-a03340c458dc)

대략적으로 수정해봤습니다
