### ISSUE TITLE
[BUG]탄환창 이슈

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#95]
**이슈 요약**
[무기 관련] 버그 요약 한줄로 작성
탄환 UI 오른쪽의 표시 내용이 다름

**이슈 내용**
남은 탄환창 우측에는 탄창 크기가 아니라 무기 변경창에 표시되는 이미지 처럼 가지고 있는 총알이 보여져야 한다.

**재현 스텝**
: 스텝별로 상세하게 작성
1. 게임 시작후 컷신이 지나가면
2. 
3. 
4. 

**일자**
날짜 작성

**Comment by Z1758** [comment]
![제목 없음](https://github.com/user-attachments/assets/fe9d7ac5-c19e-4280-96eb-8fcffd73fdac)
수정했습니다

**Comment by jgb0222** [comment]
감사합니다
