### ISSUE TITLE
[BUG] 사슴 체력 이슈

### ISSUE THREAD

**Issue by jgb0222** [leesiyeon99/Project-AK#96]
**이슈 요약**
[적] 버그 요약 한줄로 작성
한방에 사슴이 죽음
**이슈 내용**
체력이 50이라 공격력이 25인 연사 무기에게는 죽을 일이 없는데 죽게 된다.

**재현 스텝**
: 스텝별로 상세하게 작성
1. 사슴 사격 시
2. 
3. 
4. 

**일자**
날짜 작성

**Comment by Z1758** [comment]
비고에  무조건 한 방만 맞아도 죽는다기에 한방 처리 했습니다

**Comment by jgb0222** [comment]
네 알겠습니다
